app = 'west-coast-healthy-memory-society'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'  # Increased memory a bit for Next.js
  cpu_kind = 'shared'
  cpus = 1

# Removed the MySQL configuration since it's external now
